### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [maybenextime/RBTree#1]
Ваше решение довольно сильно похоже на уже имеющиеся в интернете решения:
  - https://github.com/cjmp1/PS/blob/e8043c14ca489de15693e1da62fa57cab7e641a4/DataStructure/RedBlackTree.cpp
 - https://github.com/GSDante/RBTree/blob/master/RBtree.cpp

Списанные задания нелься сдать в качестве курсового проекта, а переименовывание функций и переменных не является достаточным объёмом самостоятельной работы для курсового проекта. Предлагаю вам завтра получить новый вариант задания, который вы будете сдавать уже в сентябре. Права на автомат за экзамен вы также лишаетесь (придётся сдавать экзамен также в сентябре).

**Comment by maybenextime** [comment]
Здравствуйте!
Я не посмотел код на этих сайтах. Я прочитал алгоритм в интернете я написал по тем, что я понял. Вы можете проверить ещё раз, пожалуйста.

**Comment by gagarski** [comment]
Не утверждаю, что вы списали конкретно отсюда, но первоисточник у вас и у тех репозиториев явно общий (а код там появился раньше).

Код у вас весьма специфический и я не поверю, что по описанию случайно можно написать точно такой же (а он совпадает кроме имён переменных и функций) ещё раз, разве что в этом описании алгоритма напрямую присутствовали этот код (что тоже считается списыванием). Можете привести источник, где вы прочитали описание алогоритма, хотя вы вряд ли меня переубедите.
